# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import listener_pb2 as listener__pb2
import reflector_pb2 as reflector__pb2
import calculator_pb2 as calculator__pb2

from listener_pb2 import *
from reflector_pb2 import *
from calculator_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\tapi.proto\x1a\x0elistener.proto\x1a\x0freflector.proto\x1a\x10\x63\x61lculator.protoP\x00P\x01P\x02\x62\x06proto3')
  ,
  dependencies=[listener__pb2.DESCRIPTOR,reflector__pb2.DESCRIPTOR,calculator__pb2.DESCRIPTOR,],
  public_dependencies=[listener__pb2.DESCRIPTOR,reflector__pb2.DESCRIPTOR,calculator__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
