# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calculator.proto',
  package='Calculator',
  syntax='proto3',
  serialized_pb=_b('\n\x10\x63\x61lculator.proto\x12\nCalculator\"&\n\nAddRequest\x12\x0b\n\x03lhs\x18\x01 \x01(\x05\x12\x0b\n\x03rhs\x18\x02 \x01(\x05\"\x1a\n\tAddResult\x12\r\n\x05value\x18\x01 \x01(\x05\"&\n\nSubRequest\x12\x0b\n\x03lhs\x18\x01 \x01(\x05\x12\x0b\n\x03rhs\x18\x02 \x01(\x05\"\x1a\n\tSubResult\x12\r\n\x05value\x18\x01 \x01(\x05\"&\n\nMulRequest\x12\x0b\n\x03lhs\x18\x01 \x01(\x05\x12\x0b\n\x03rhs\x18\x02 \x01(\x05\"\x1a\n\tMulResult\x12\r\n\x05value\x18\x01 \x01(\x05\"&\n\nDivRequest\x12\x0b\n\x03lhs\x18\x01 \x01(\x05\x12\x0b\n\x03rhs\x18\x02 \x01(\x05\"\x1a\n\tDivResult\x12\r\n\x05value\x18\x01 \x01(\x05\x32\xe1\x01\n\x07Service\x12\x34\n\x03\x61\x64\x64\x12\x16.Calculator.AddRequest\x1a\x15.Calculator.AddResult\x12\x34\n\x03sub\x12\x16.Calculator.SubRequest\x1a\x15.Calculator.SubResult\x12\x34\n\x03mul\x12\x16.Calculator.MulRequest\x1a\x15.Calculator.MulResult\x12\x34\n\x03\x64iv\x12\x16.Calculator.DivRequest\x1a\x15.Calculator.DivResultb\x06proto3')
)




_ADDREQUEST = _descriptor.Descriptor(
  name='AddRequest',
  full_name='Calculator.AddRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lhs', full_name='Calculator.AddRequest.lhs', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rhs', full_name='Calculator.AddRequest.rhs', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=70,
)


_ADDRESULT = _descriptor.Descriptor(
  name='AddResult',
  full_name='Calculator.AddResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Calculator.AddResult.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=98,
)


_SUBREQUEST = _descriptor.Descriptor(
  name='SubRequest',
  full_name='Calculator.SubRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lhs', full_name='Calculator.SubRequest.lhs', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rhs', full_name='Calculator.SubRequest.rhs', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=138,
)


_SUBRESULT = _descriptor.Descriptor(
  name='SubResult',
  full_name='Calculator.SubResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Calculator.SubResult.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=166,
)


_MULREQUEST = _descriptor.Descriptor(
  name='MulRequest',
  full_name='Calculator.MulRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lhs', full_name='Calculator.MulRequest.lhs', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rhs', full_name='Calculator.MulRequest.rhs', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=206,
)


_MULRESULT = _descriptor.Descriptor(
  name='MulResult',
  full_name='Calculator.MulResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Calculator.MulResult.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=234,
)


_DIVREQUEST = _descriptor.Descriptor(
  name='DivRequest',
  full_name='Calculator.DivRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lhs', full_name='Calculator.DivRequest.lhs', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rhs', full_name='Calculator.DivRequest.rhs', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=274,
)


_DIVRESULT = _descriptor.Descriptor(
  name='DivResult',
  full_name='Calculator.DivResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Calculator.DivResult.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=302,
)

DESCRIPTOR.message_types_by_name['AddRequest'] = _ADDREQUEST
DESCRIPTOR.message_types_by_name['AddResult'] = _ADDRESULT
DESCRIPTOR.message_types_by_name['SubRequest'] = _SUBREQUEST
DESCRIPTOR.message_types_by_name['SubResult'] = _SUBRESULT
DESCRIPTOR.message_types_by_name['MulRequest'] = _MULREQUEST
DESCRIPTOR.message_types_by_name['MulResult'] = _MULRESULT
DESCRIPTOR.message_types_by_name['DivRequest'] = _DIVREQUEST
DESCRIPTOR.message_types_by_name['DivResult'] = _DIVRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddRequest = _reflection.GeneratedProtocolMessageType('AddRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDREQUEST,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:Calculator.AddRequest)
  ))
_sym_db.RegisterMessage(AddRequest)

AddResult = _reflection.GeneratedProtocolMessageType('AddResult', (_message.Message,), dict(
  DESCRIPTOR = _ADDRESULT,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:Calculator.AddResult)
  ))
_sym_db.RegisterMessage(AddResult)

SubRequest = _reflection.GeneratedProtocolMessageType('SubRequest', (_message.Message,), dict(
  DESCRIPTOR = _SUBREQUEST,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:Calculator.SubRequest)
  ))
_sym_db.RegisterMessage(SubRequest)

SubResult = _reflection.GeneratedProtocolMessageType('SubResult', (_message.Message,), dict(
  DESCRIPTOR = _SUBRESULT,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:Calculator.SubResult)
  ))
_sym_db.RegisterMessage(SubResult)

MulRequest = _reflection.GeneratedProtocolMessageType('MulRequest', (_message.Message,), dict(
  DESCRIPTOR = _MULREQUEST,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:Calculator.MulRequest)
  ))
_sym_db.RegisterMessage(MulRequest)

MulResult = _reflection.GeneratedProtocolMessageType('MulResult', (_message.Message,), dict(
  DESCRIPTOR = _MULRESULT,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:Calculator.MulResult)
  ))
_sym_db.RegisterMessage(MulResult)

DivRequest = _reflection.GeneratedProtocolMessageType('DivRequest', (_message.Message,), dict(
  DESCRIPTOR = _DIVREQUEST,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:Calculator.DivRequest)
  ))
_sym_db.RegisterMessage(DivRequest)

DivResult = _reflection.GeneratedProtocolMessageType('DivResult', (_message.Message,), dict(
  DESCRIPTOR = _DIVRESULT,
  __module__ = 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:Calculator.DivResult)
  ))
_sym_db.RegisterMessage(DivResult)



_SERVICE = _descriptor.ServiceDescriptor(
  name='Service',
  full_name='Calculator.Service',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=305,
  serialized_end=530,
  methods=[
  _descriptor.MethodDescriptor(
    name='add',
    full_name='Calculator.Service.add',
    index=0,
    containing_service=None,
    input_type=_ADDREQUEST,
    output_type=_ADDRESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sub',
    full_name='Calculator.Service.sub',
    index=1,
    containing_service=None,
    input_type=_SUBREQUEST,
    output_type=_SUBRESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='mul',
    full_name='Calculator.Service.mul',
    index=2,
    containing_service=None,
    input_type=_MULREQUEST,
    output_type=_MULRESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='div',
    full_name='Calculator.Service.div',
    index=3,
    containing_service=None,
    input_type=_DIVREQUEST,
    output_type=_DIVRESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICE)

DESCRIPTOR.services_by_name['Service'] = _SERVICE

# @@protoc_insertion_point(module_scope)
