// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calculator.proto

#ifndef PROTOBUF_calculator_2eproto__INCLUDED
#define PROTOBUF_calculator_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace Calculator {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_calculator_2eproto();
void protobuf_AssignDesc_calculator_2eproto();
void protobuf_ShutdownFile_calculator_2eproto();

class AddRequest;
class AddResult;
class DivRequest;
class DivResult;
class MulRequest;
class MulResult;
class SubRequest;
class SubResult;

// ===================================================================

class AddRequest : public ::google::protobuf::Message {
 public:
  AddRequest();
  virtual ~AddRequest();

  AddRequest(const AddRequest& from);

  inline AddRequest& operator=(const AddRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AddRequest& default_instance();

  void Swap(AddRequest* other);

  // implements Message ----------------------------------------------

  inline AddRequest* New() const { return New(NULL); }

  AddRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AddRequest& from);
  void MergeFrom(const AddRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AddRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 lhs = 1;
  void clear_lhs();
  static const int kLhsFieldNumber = 1;
  ::google::protobuf::int32 lhs() const;
  void set_lhs(::google::protobuf::int32 value);

  // optional int32 rhs = 2;
  void clear_rhs();
  static const int kRhsFieldNumber = 2;
  ::google::protobuf::int32 rhs() const;
  void set_rhs(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Calculator.AddRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 lhs_;
  ::google::protobuf::int32 rhs_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_calculator_2eproto();
  friend void protobuf_AssignDesc_calculator_2eproto();
  friend void protobuf_ShutdownFile_calculator_2eproto();

  void InitAsDefaultInstance();
  static AddRequest* default_instance_;
};
// -------------------------------------------------------------------

class AddResult : public ::google::protobuf::Message {
 public:
  AddResult();
  virtual ~AddResult();

  AddResult(const AddResult& from);

  inline AddResult& operator=(const AddResult& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AddResult& default_instance();

  void Swap(AddResult* other);

  // implements Message ----------------------------------------------

  inline AddResult* New() const { return New(NULL); }

  AddResult* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const AddResult& from);
  void MergeFrom(const AddResult& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AddResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  ::google::protobuf::int32 value() const;
  void set_value(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Calculator.AddResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 value_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_calculator_2eproto();
  friend void protobuf_AssignDesc_calculator_2eproto();
  friend void protobuf_ShutdownFile_calculator_2eproto();

  void InitAsDefaultInstance();
  static AddResult* default_instance_;
};
// -------------------------------------------------------------------

class SubRequest : public ::google::protobuf::Message {
 public:
  SubRequest();
  virtual ~SubRequest();

  SubRequest(const SubRequest& from);

  inline SubRequest& operator=(const SubRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SubRequest& default_instance();

  void Swap(SubRequest* other);

  // implements Message ----------------------------------------------

  inline SubRequest* New() const { return New(NULL); }

  SubRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SubRequest& from);
  void MergeFrom(const SubRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SubRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 lhs = 1;
  void clear_lhs();
  static const int kLhsFieldNumber = 1;
  ::google::protobuf::int32 lhs() const;
  void set_lhs(::google::protobuf::int32 value);

  // optional int32 rhs = 2;
  void clear_rhs();
  static const int kRhsFieldNumber = 2;
  ::google::protobuf::int32 rhs() const;
  void set_rhs(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Calculator.SubRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 lhs_;
  ::google::protobuf::int32 rhs_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_calculator_2eproto();
  friend void protobuf_AssignDesc_calculator_2eproto();
  friend void protobuf_ShutdownFile_calculator_2eproto();

  void InitAsDefaultInstance();
  static SubRequest* default_instance_;
};
// -------------------------------------------------------------------

class SubResult : public ::google::protobuf::Message {
 public:
  SubResult();
  virtual ~SubResult();

  SubResult(const SubResult& from);

  inline SubResult& operator=(const SubResult& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SubResult& default_instance();

  void Swap(SubResult* other);

  // implements Message ----------------------------------------------

  inline SubResult* New() const { return New(NULL); }

  SubResult* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SubResult& from);
  void MergeFrom(const SubResult& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SubResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  ::google::protobuf::int32 value() const;
  void set_value(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Calculator.SubResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 value_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_calculator_2eproto();
  friend void protobuf_AssignDesc_calculator_2eproto();
  friend void protobuf_ShutdownFile_calculator_2eproto();

  void InitAsDefaultInstance();
  static SubResult* default_instance_;
};
// -------------------------------------------------------------------

class MulRequest : public ::google::protobuf::Message {
 public:
  MulRequest();
  virtual ~MulRequest();

  MulRequest(const MulRequest& from);

  inline MulRequest& operator=(const MulRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MulRequest& default_instance();

  void Swap(MulRequest* other);

  // implements Message ----------------------------------------------

  inline MulRequest* New() const { return New(NULL); }

  MulRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MulRequest& from);
  void MergeFrom(const MulRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MulRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 lhs = 1;
  void clear_lhs();
  static const int kLhsFieldNumber = 1;
  ::google::protobuf::int32 lhs() const;
  void set_lhs(::google::protobuf::int32 value);

  // optional int32 rhs = 2;
  void clear_rhs();
  static const int kRhsFieldNumber = 2;
  ::google::protobuf::int32 rhs() const;
  void set_rhs(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Calculator.MulRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 lhs_;
  ::google::protobuf::int32 rhs_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_calculator_2eproto();
  friend void protobuf_AssignDesc_calculator_2eproto();
  friend void protobuf_ShutdownFile_calculator_2eproto();

  void InitAsDefaultInstance();
  static MulRequest* default_instance_;
};
// -------------------------------------------------------------------

class MulResult : public ::google::protobuf::Message {
 public:
  MulResult();
  virtual ~MulResult();

  MulResult(const MulResult& from);

  inline MulResult& operator=(const MulResult& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MulResult& default_instance();

  void Swap(MulResult* other);

  // implements Message ----------------------------------------------

  inline MulResult* New() const { return New(NULL); }

  MulResult* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MulResult& from);
  void MergeFrom(const MulResult& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MulResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  ::google::protobuf::int32 value() const;
  void set_value(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Calculator.MulResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 value_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_calculator_2eproto();
  friend void protobuf_AssignDesc_calculator_2eproto();
  friend void protobuf_ShutdownFile_calculator_2eproto();

  void InitAsDefaultInstance();
  static MulResult* default_instance_;
};
// -------------------------------------------------------------------

class DivRequest : public ::google::protobuf::Message {
 public:
  DivRequest();
  virtual ~DivRequest();

  DivRequest(const DivRequest& from);

  inline DivRequest& operator=(const DivRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DivRequest& default_instance();

  void Swap(DivRequest* other);

  // implements Message ----------------------------------------------

  inline DivRequest* New() const { return New(NULL); }

  DivRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DivRequest& from);
  void MergeFrom(const DivRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DivRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 lhs = 1;
  void clear_lhs();
  static const int kLhsFieldNumber = 1;
  ::google::protobuf::int32 lhs() const;
  void set_lhs(::google::protobuf::int32 value);

  // optional int32 rhs = 2;
  void clear_rhs();
  static const int kRhsFieldNumber = 2;
  ::google::protobuf::int32 rhs() const;
  void set_rhs(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Calculator.DivRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 lhs_;
  ::google::protobuf::int32 rhs_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_calculator_2eproto();
  friend void protobuf_AssignDesc_calculator_2eproto();
  friend void protobuf_ShutdownFile_calculator_2eproto();

  void InitAsDefaultInstance();
  static DivRequest* default_instance_;
};
// -------------------------------------------------------------------

class DivResult : public ::google::protobuf::Message {
 public:
  DivResult();
  virtual ~DivResult();

  DivResult(const DivResult& from);

  inline DivResult& operator=(const DivResult& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const DivResult& default_instance();

  void Swap(DivResult* other);

  // implements Message ----------------------------------------------

  inline DivResult* New() const { return New(NULL); }

  DivResult* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const DivResult& from);
  void MergeFrom(const DivResult& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DivResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int32 value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  ::google::protobuf::int32 value() const;
  void set_value(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Calculator.DivResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::int32 value_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_calculator_2eproto();
  friend void protobuf_AssignDesc_calculator_2eproto();
  friend void protobuf_ShutdownFile_calculator_2eproto();

  void InitAsDefaultInstance();
  static DivResult* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// AddRequest

// optional int32 lhs = 1;
inline void AddRequest::clear_lhs() {
  lhs_ = 0;
}
inline ::google::protobuf::int32 AddRequest::lhs() const {
  // @@protoc_insertion_point(field_get:Calculator.AddRequest.lhs)
  return lhs_;
}
inline void AddRequest::set_lhs(::google::protobuf::int32 value) {
  
  lhs_ = value;
  // @@protoc_insertion_point(field_set:Calculator.AddRequest.lhs)
}

// optional int32 rhs = 2;
inline void AddRequest::clear_rhs() {
  rhs_ = 0;
}
inline ::google::protobuf::int32 AddRequest::rhs() const {
  // @@protoc_insertion_point(field_get:Calculator.AddRequest.rhs)
  return rhs_;
}
inline void AddRequest::set_rhs(::google::protobuf::int32 value) {
  
  rhs_ = value;
  // @@protoc_insertion_point(field_set:Calculator.AddRequest.rhs)
}

// -------------------------------------------------------------------

// AddResult

// optional int32 value = 1;
inline void AddResult::clear_value() {
  value_ = 0;
}
inline ::google::protobuf::int32 AddResult::value() const {
  // @@protoc_insertion_point(field_get:Calculator.AddResult.value)
  return value_;
}
inline void AddResult::set_value(::google::protobuf::int32 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:Calculator.AddResult.value)
}

// -------------------------------------------------------------------

// SubRequest

// optional int32 lhs = 1;
inline void SubRequest::clear_lhs() {
  lhs_ = 0;
}
inline ::google::protobuf::int32 SubRequest::lhs() const {
  // @@protoc_insertion_point(field_get:Calculator.SubRequest.lhs)
  return lhs_;
}
inline void SubRequest::set_lhs(::google::protobuf::int32 value) {
  
  lhs_ = value;
  // @@protoc_insertion_point(field_set:Calculator.SubRequest.lhs)
}

// optional int32 rhs = 2;
inline void SubRequest::clear_rhs() {
  rhs_ = 0;
}
inline ::google::protobuf::int32 SubRequest::rhs() const {
  // @@protoc_insertion_point(field_get:Calculator.SubRequest.rhs)
  return rhs_;
}
inline void SubRequest::set_rhs(::google::protobuf::int32 value) {
  
  rhs_ = value;
  // @@protoc_insertion_point(field_set:Calculator.SubRequest.rhs)
}

// -------------------------------------------------------------------

// SubResult

// optional int32 value = 1;
inline void SubResult::clear_value() {
  value_ = 0;
}
inline ::google::protobuf::int32 SubResult::value() const {
  // @@protoc_insertion_point(field_get:Calculator.SubResult.value)
  return value_;
}
inline void SubResult::set_value(::google::protobuf::int32 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:Calculator.SubResult.value)
}

// -------------------------------------------------------------------

// MulRequest

// optional int32 lhs = 1;
inline void MulRequest::clear_lhs() {
  lhs_ = 0;
}
inline ::google::protobuf::int32 MulRequest::lhs() const {
  // @@protoc_insertion_point(field_get:Calculator.MulRequest.lhs)
  return lhs_;
}
inline void MulRequest::set_lhs(::google::protobuf::int32 value) {
  
  lhs_ = value;
  // @@protoc_insertion_point(field_set:Calculator.MulRequest.lhs)
}

// optional int32 rhs = 2;
inline void MulRequest::clear_rhs() {
  rhs_ = 0;
}
inline ::google::protobuf::int32 MulRequest::rhs() const {
  // @@protoc_insertion_point(field_get:Calculator.MulRequest.rhs)
  return rhs_;
}
inline void MulRequest::set_rhs(::google::protobuf::int32 value) {
  
  rhs_ = value;
  // @@protoc_insertion_point(field_set:Calculator.MulRequest.rhs)
}

// -------------------------------------------------------------------

// MulResult

// optional int32 value = 1;
inline void MulResult::clear_value() {
  value_ = 0;
}
inline ::google::protobuf::int32 MulResult::value() const {
  // @@protoc_insertion_point(field_get:Calculator.MulResult.value)
  return value_;
}
inline void MulResult::set_value(::google::protobuf::int32 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:Calculator.MulResult.value)
}

// -------------------------------------------------------------------

// DivRequest

// optional int32 lhs = 1;
inline void DivRequest::clear_lhs() {
  lhs_ = 0;
}
inline ::google::protobuf::int32 DivRequest::lhs() const {
  // @@protoc_insertion_point(field_get:Calculator.DivRequest.lhs)
  return lhs_;
}
inline void DivRequest::set_lhs(::google::protobuf::int32 value) {
  
  lhs_ = value;
  // @@protoc_insertion_point(field_set:Calculator.DivRequest.lhs)
}

// optional int32 rhs = 2;
inline void DivRequest::clear_rhs() {
  rhs_ = 0;
}
inline ::google::protobuf::int32 DivRequest::rhs() const {
  // @@protoc_insertion_point(field_get:Calculator.DivRequest.rhs)
  return rhs_;
}
inline void DivRequest::set_rhs(::google::protobuf::int32 value) {
  
  rhs_ = value;
  // @@protoc_insertion_point(field_set:Calculator.DivRequest.rhs)
}

// -------------------------------------------------------------------

// DivResult

// optional int32 value = 1;
inline void DivResult::clear_value() {
  value_ = 0;
}
inline ::google::protobuf::int32 DivResult::value() const {
  // @@protoc_insertion_point(field_get:Calculator.DivResult.value)
  return value_;
}
inline void DivResult::set_value(::google::protobuf::int32 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:Calculator.DivResult.value)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Calculator

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_calculator_2eproto__INCLUDED
