# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reflector.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='reflector.proto',
  package='Reflector',
  syntax='proto3',
  serialized_pb=_b('\n\x0freflector.proto\x12\tReflector\"\x1f\n\nAckRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\"\x1e\n\tAckResult\x12\x11\n\ttimestamp\x18\x01 \x01(\t2=\n\x07Service\x12\x32\n\x03\x61\x63k\x12\x15.Reflector.AckRequest\x1a\x14.Reflector.AckResultb\x06proto3')
)




_ACKREQUEST = _descriptor.Descriptor(
  name='AckRequest',
  full_name='Reflector.AckRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Reflector.AckRequest.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=61,
)


_ACKRESULT = _descriptor.Descriptor(
  name='AckResult',
  full_name='Reflector.AckResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Reflector.AckResult.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=93,
)

DESCRIPTOR.message_types_by_name['AckRequest'] = _ACKREQUEST
DESCRIPTOR.message_types_by_name['AckResult'] = _ACKRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AckRequest = _reflection.GeneratedProtocolMessageType('AckRequest', (_message.Message,), dict(
  DESCRIPTOR = _ACKREQUEST,
  __module__ = 'reflector_pb2'
  # @@protoc_insertion_point(class_scope:Reflector.AckRequest)
  ))
_sym_db.RegisterMessage(AckRequest)

AckResult = _reflection.GeneratedProtocolMessageType('AckResult', (_message.Message,), dict(
  DESCRIPTOR = _ACKRESULT,
  __module__ = 'reflector_pb2'
  # @@protoc_insertion_point(class_scope:Reflector.AckResult)
  ))
_sym_db.RegisterMessage(AckResult)



_SERVICE = _descriptor.ServiceDescriptor(
  name='Service',
  full_name='Reflector.Service',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=95,
  serialized_end=156,
  methods=[
  _descriptor.MethodDescriptor(
    name='ack',
    full_name='Reflector.Service.ack',
    index=0,
    containing_service=None,
    input_type=_ACKREQUEST,
    output_type=_ACKRESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICE)

DESCRIPTOR.services_by_name['Service'] = _SERVICE

# @@protoc_insertion_point(module_scope)
